#!/bin/bash
set -e;
APP=$2
DB_IMAGE=jmca/mariadb
DATABASE_NAME="${APP}_production"

# Get the ID of the currently running MariaDB container, if any
id=$(docker ps | grep "$DB_IMAGE":latest |  awk '{print $1}')

case $1 in
  mdbsingle:status)
    if [[ "$id" != "" ]]; then
      echo "MariaDB container running with ID: ${id}"
    else
      echo "MariaDB container is not running"
    fi
    ;;

  help)
    cat && cat<<EOF
    mdbsingle:status            Status of mariadb container
    ;;
EOF
esac
cat
