#!/bin/bash

# Build MariaDB image
DB_IMAGE="marceldegraaf/mariadb"

echo "Building MariaDB image for Docker. This may take a while. Use \`docker ps\` to see what's happening."
docker build -q=true -t "$DB_IMAGE" github.com/Kloadut/dokku-md-dockerfiles
